     name: Publish Package

     on:
       push:
         branches:
           - master

     jobs:
       publish:
         runs-on: ubuntu-latest
         steps:
           - name: Checkout code
             uses: actions/checkout@v2

           - name: Set up Node.js
             uses: actions/setup-node@v2
             with:
               node-version: '20.18.0'  # используйте нужную версию Node.js
               registry-url: 'https://registry.npmjs.org'

           - name: Install dependencies
             run: npm install

           - name: Build package
             run: npm run build
            
           - name: Semantic Release
             run: npx semantic-release
               env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
     permissions:
      contents: write
      pages: write
      id-token: write
